/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file_transfer.h"

bool_t
xdr_file (XDR *xdrs, file *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->file_name, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->file_content, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
