/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file_transfer.h"

FILE *fr;

int *
send_file_1_svc(file *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("File name received!: %s\n", argp->file_name);
	fr = fopen(argp->file_name,"w");
	fprintf(fr,"%s",argp->file_content);
	fflush(stdin);
	fclose(fr);
	printf("File received successfully\n");
	
	result = 1;
	return &result;
}
